parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symblog
    database_user: Thomas
    database_password: e6627
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 71ee9f691d6575b853992afe617f16d19db43041
    database_path: null
