Blogger\BlogBundle\Entity\Comment:
    type: entity
    table: comment
    repositoryClass: Blogger\BlogBundle\Entity\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        user:
            type: string
            length: 255
        comment:
            type: text
        approved:
            type: boolean
        created:
            type: datetime
        updated:
            type: datetime
    manyToOne:
        blog:
            targetEntity: Blog
            inversedBy: comments
            joinColumn:
                name: blog_id
                referencedColumnName: id
    lifecycleCallbacks: 
        preUpdate: [setUpdatedValue]
            
